inherit_from:
  - .rubocop_airbnb.yml

require: rubocop-rspec

Metrics/BlockLength:
  ExcludedMethods: ['describe', 'context']

RSpec/ContextWording:
  Enabled: false

RSpec/ExampleWording:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

Metrics/LineLength:
  Enabled: false

AllCops:
  Exclude:
    - 'node_modules/**/*'
    - 'vendor/**/*'
    - 'bin/**/*'
